// Generated by scripts/generate-amapi-policy-schema.mjs. Do not edit manually.
// Refresh deliberately with `npm run amapi-schema:update` and review the schema diff.
export const AMAPI_POLICY_DISCOVERY_SCHEMA = {
  "source": "https://androidmanagement.googleapis.com/$discovery/rest?version=v1",
  "revision": "20260910",
  "root": "Policy",
  "schemas": {
    "AdvancedSecurityOverrides": {
      "type": "object",
      "properties": {
        "commonCriteriaMode": {
          "type": "string",
          "enum": [
            "COMMON_CRITERIA_MODE_UNSPECIFIED",
            "COMMON_CRITERIA_MODE_DISABLED",
            "COMMON_CRITERIA_MODE_ENABLED"
          ]
        },
        "contentProtectionPolicy": {
          "type": "string",
          "enum": [
            "CONTENT_PROTECTION_POLICY_UNSPECIFIED",
            "CONTENT_PROTECTION_DISABLED",
            "CONTENT_PROTECTION_ENFORCED",
            "CONTENT_PROTECTION_USER_CHOICE"
          ]
        },
        "developerSettings": {
          "type": "string",
          "enum": [
            "DEVELOPER_SETTINGS_UNSPECIFIED",
            "DEVELOPER_SETTINGS_DISABLED",
            "DEVELOPER_SETTINGS_ALLOWED"
          ]
        },
        "googlePlayProtectVerifyApps": {
          "type": "string",
          "enum": [
            "GOOGLE_PLAY_PROTECT_VERIFY_APPS_UNSPECIFIED",
            "VERIFY_APPS_ENFORCED",
            "VERIFY_APPS_USER_CHOICE"
          ]
        },
        "mtePolicy": {
          "type": "string",
          "enum": [
            "MTE_POLICY_UNSPECIFIED",
            "MTE_USER_CHOICE",
            "MTE_ENFORCED",
            "MTE_DISABLED"
          ]
        },
        "personalAppsThatCanReadWorkNotifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "untrustedAppsPolicy": {
          "type": "string",
          "enum": [
            "UNTRUSTED_APPS_POLICY_UNSPECIFIED",
            "DISALLOW_INSTALL",
            "ALLOW_INSTALL_IN_PERSONAL_PROFILE_ONLY",
            "ALLOW_INSTALL_DEVICE_WIDE"
          ]
        }
      }
    },
    "AlwaysOnVpnPackage": {
      "type": "object",
      "properties": {
        "lockdownEnabled": {
          "type": "boolean"
        },
        "packageName": {
          "type": "string"
        }
      }
    },
    "ApiLevelCondition": {
      "type": "object",
      "properties": {
        "minApiLevel": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "ApnPolicy": {
      "type": "object",
      "properties": {
        "apnSettings": {
          "type": "array",
          "items": {
            "$ref": "ApnSetting"
          }
        },
        "overrideApns": {
          "type": "string",
          "enum": [
            "OVERRIDE_APNS_UNSPECIFIED",
            "OVERRIDE_APNS_DISABLED",
            "OVERRIDE_APNS_ENABLED"
          ]
        }
      }
    },
    "ApnSetting": {
      "type": "object",
      "properties": {
        "alwaysOnSetting": {
          "type": "string",
          "enum": [
            "ALWAYS_ON_SETTING_UNSPECIFIED",
            "NOT_ALWAYS_ON",
            "ALWAYS_ON"
          ]
        },
        "apn": {
          "type": "string"
        },
        "apnTypes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "APN_TYPE_UNSPECIFIED",
              "ENTERPRISE",
              "BIP",
              "CBS",
              "DEFAULT",
              "DUN",
              "EMERGENCY",
              "FOTA",
              "HIPRI",
              "IA",
              "IMS",
              "MCX",
              "MMS",
              "RCS",
              "SUPL",
              "VSIM",
              "XCAP"
            ]
          }
        },
        "authType": {
          "type": "string",
          "enum": [
            "AUTH_TYPE_UNSPECIFIED",
            "NONE",
            "PAP",
            "CHAP",
            "PAP_OR_CHAP"
          ]
        },
        "carrierId": {
          "type": "integer",
          "format": "int32"
        },
        "displayName": {
          "type": "string"
        },
        "mmsc": {
          "type": "string"
        },
        "mmsProxyAddress": {
          "type": "string"
        },
        "mmsProxyPort": {
          "type": "integer",
          "format": "int32"
        },
        "mtuV4": {
          "type": "integer",
          "format": "int32"
        },
        "mtuV6": {
          "type": "integer",
          "format": "int32"
        },
        "mvnoType": {
          "type": "string",
          "enum": [
            "MVNO_TYPE_UNSPECIFIED",
            "GID",
            "ICCID",
            "IMSI",
            "SPN"
          ]
        },
        "networkTypes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "NETWORK_TYPE_UNSPECIFIED",
              "EDGE",
              "GPRS",
              "GSM",
              "HSDPA",
              "HSPA",
              "HSPAP",
              "HSUPA",
              "IWLAN",
              "LTE",
              "NR",
              "TD_SCDMA",
              "UMTS"
            ]
          }
        },
        "numericOperatorId": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "protocol": {
          "type": "string",
          "enum": [
            "PROTOCOL_UNSPECIFIED",
            "IP",
            "IPV4V6",
            "IPV6",
            "NON_IP",
            "PPP",
            "UNSTRUCTURED"
          ]
        },
        "proxyAddress": {
          "type": "string"
        },
        "proxyPort": {
          "type": "integer",
          "format": "int32"
        },
        "roamingProtocol": {
          "type": "string",
          "enum": [
            "PROTOCOL_UNSPECIFIED",
            "IP",
            "IPV4V6",
            "IPV6",
            "NON_IP",
            "PPP",
            "UNSTRUCTURED"
          ]
        },
        "username": {
          "type": "string"
        }
      }
    },
    "ApplicationPolicy": {
      "type": "object",
      "properties": {
        "accessibleTrackIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "alwaysOnVpnLockdownExemption": {
          "type": "string",
          "enum": [
            "ALWAYS_ON_VPN_LOCKDOWN_EXEMPTION_UNSPECIFIED",
            "VPN_LOCKDOWN_ENFORCED",
            "VPN_LOCKDOWN_EXEMPTION"
          ]
        },
        "autoUpdateMode": {
          "type": "string",
          "enum": [
            "AUTO_UPDATE_MODE_UNSPECIFIED",
            "AUTO_UPDATE_DEFAULT",
            "AUTO_UPDATE_POSTPONED",
            "AUTO_UPDATE_HIGH_PRIORITY"
          ]
        },
        "connectedWorkAndPersonalApp": {
          "type": "string",
          "enum": [
            "CONNECTED_WORK_AND_PERSONAL_APP_UNSPECIFIED",
            "CONNECTED_WORK_AND_PERSONAL_APP_DISALLOWED",
            "CONNECTED_WORK_AND_PERSONAL_APP_ALLOWED"
          ]
        },
        "credentialProviderPolicy": {
          "type": "string",
          "enum": [
            "CREDENTIAL_PROVIDER_POLICY_UNSPECIFIED",
            "CREDENTIAL_PROVIDER_ALLOWED",
            "CREDENTIAL_PROVIDER_DISALLOWED"
          ]
        },
        "customAppConfig": {
          "$ref": "CustomAppConfig"
        },
        "defaultPermissionPolicy": {
          "type": "string",
          "enum": [
            "PERMISSION_POLICY_UNSPECIFIED",
            "PROMPT",
            "GRANT",
            "DENY"
          ]
        },
        "delegatedScopes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "DELEGATED_SCOPE_UNSPECIFIED",
              "CERT_INSTALL",
              "MANAGED_CONFIGURATIONS",
              "BLOCK_UNINSTALL",
              "PERMISSION_GRANT",
              "PACKAGE_ACCESS",
              "ENABLE_SYSTEM_APP",
              "NETWORK_ACTIVITY_LOGS",
              "SECURITY_LOGS",
              "CERT_SELECTION"
            ]
          }
        },
        "disabled": {
          "type": "boolean"
        },
        "extensionConfig": {
          "$ref": "ExtensionConfig"
        },
        "installConstraint": {
          "type": "array",
          "items": {
            "$ref": "InstallConstraint"
          }
        },
        "installPriority": {
          "type": "integer",
          "format": "int32"
        },
        "installType": {
          "type": "string",
          "enum": [
            "INSTALL_TYPE_UNSPECIFIED",
            "PREINSTALLED",
            "FORCE_INSTALLED",
            "BLOCKED",
            "AVAILABLE",
            "REQUIRED_FOR_SETUP",
            "KIOSK",
            "CUSTOM"
          ]
        },
        "lockTaskAllowed": {
          "type": "boolean"
        },
        "managedConfiguration": {
          "type": "object",
          "additionalProperties": {
            "type": "any"
          }
        },
        "managedConfigurationTemplate": {
          "$ref": "ManagedConfigurationTemplate"
        },
        "minimumVersionCode": {
          "type": "integer",
          "format": "int32"
        },
        "packageName": {
          "type": "string"
        },
        "permissionGrants": {
          "type": "array",
          "items": {
            "$ref": "PermissionGrant"
          }
        },
        "preferentialNetworkId": {
          "type": "string",
          "enum": [
            "PREFERENTIAL_NETWORK_ID_UNSPECIFIED",
            "NO_PREFERENTIAL_NETWORK",
            "PREFERENTIAL_NETWORK_ID_ONE",
            "PREFERENTIAL_NETWORK_ID_TWO",
            "PREFERENTIAL_NETWORK_ID_THREE",
            "PREFERENTIAL_NETWORK_ID_FOUR",
            "PREFERENTIAL_NETWORK_ID_FIVE"
          ]
        },
        "roles": {
          "type": "array",
          "items": {
            "$ref": "Role"
          }
        },
        "signingKeyCerts": {
          "type": "array",
          "items": {
            "$ref": "ApplicationSigningKeyCert"
          }
        },
        "userControlSettings": {
          "type": "string",
          "enum": [
            "USER_CONTROL_SETTINGS_UNSPECIFIED",
            "USER_CONTROL_ALLOWED",
            "USER_CONTROL_DISALLOWED"
          ]
        },
        "workProfileWidgets": {
          "type": "string",
          "enum": [
            "WORK_PROFILE_WIDGETS_UNSPECIFIED",
            "WORK_PROFILE_WIDGETS_ALLOWED",
            "WORK_PROFILE_WIDGETS_DISALLOWED"
          ]
        }
      }
    },
    "ApplicationReportingSettings": {
      "type": "object",
      "properties": {
        "includeRemovedApps": {
          "type": "boolean"
        }
      }
    },
    "ApplicationSigningKeyCert": {
      "type": "object",
      "properties": {
        "signingKeyCertFingerprintSha256": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "BlockAction": {
      "type": "object",
      "properties": {
        "blockAfterDays": {
          "type": "integer",
          "format": "int32"
        },
        "blockScope": {
          "type": "string",
          "enum": [
            "BLOCK_SCOPE_UNSPECIFIED",
            "BLOCK_SCOPE_WORK_PROFILE",
            "BLOCK_SCOPE_DEVICE"
          ]
        }
      }
    },
    "ChoosePrivateKeyRule": {
      "type": "object",
      "properties": {
        "packageNames": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "privateKeyAlias": {
          "type": "string"
        },
        "urlPattern": {
          "type": "string"
        }
      }
    },
    "ComplianceRule": {
      "type": "object",
      "properties": {
        "apiLevelCondition": {
          "$ref": "ApiLevelCondition"
        },
        "disableApps": {
          "type": "boolean"
        },
        "nonComplianceDetailCondition": {
          "$ref": "NonComplianceDetailCondition"
        },
        "packageNamesToDisable": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "ContentProviderEndpoint": {
      "type": "object",
      "properties": {
        "packageName": {
          "type": "string"
        },
        "signingCertsSha256": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "uri": {
          "type": "string"
        }
      }
    },
    "CrossDevicePolicies": {
      "type": "object",
      "properties": {
        "nearbyAppStreaming": {
          "type": "string",
          "enum": [
            "NEARBY_APP_STREAMING_UNSPECIFIED",
            "NEARBY_APP_STREAMING_USER_CHOICE",
            "NEARBY_APP_STREAMING_DISABLED",
            "NEARBY_APP_STREAMING_USER_CHOICE_SAME_MANAGED_ACCOUNT"
          ]
        },
        "nearbyNotificationStreaming": {
          "type": "string",
          "enum": [
            "NEARBY_NOTIFICATION_STREAMING_UNSPECIFIED",
            "NEARBY_NOTIFICATION_STREAMING_USER_CHOICE",
            "NEARBY_NOTIFICATION_STREAMING_DISABLED",
            "NEARBY_NOTIFICATION_STREAMING_USER_CHOICE_SAME_MANAGED_ACCOUNT"
          ]
        }
      }
    },
    "CrossProfilePolicies": {
      "type": "object",
      "properties": {
        "crossProfileAppFunctions": {
          "type": "string",
          "enum": [
            "CROSS_PROFILE_APP_FUNCTIONS_UNSPECIFIED",
            "CROSS_PROFILE_APP_FUNCTIONS_DISALLOWED",
            "CROSS_PROFILE_APP_FUNCTIONS_ALLOWED"
          ]
        },
        "crossProfileCopyPaste": {
          "type": "string",
          "enum": [
            "CROSS_PROFILE_COPY_PASTE_UNSPECIFIED",
            "COPY_FROM_WORK_TO_PERSONAL_DISALLOWED",
            "CROSS_PROFILE_COPY_PASTE_ALLOWED"
          ]
        },
        "crossProfileDataSharing": {
          "type": "string",
          "enum": [
            "CROSS_PROFILE_DATA_SHARING_UNSPECIFIED",
            "CROSS_PROFILE_DATA_SHARING_DISALLOWED",
            "DATA_SHARING_FROM_WORK_TO_PERSONAL_DISALLOWED",
            "CROSS_PROFILE_DATA_SHARING_ALLOWED"
          ]
        },
        "exemptionsToShowWorkContactsInPersonalProfile": {
          "$ref": "PackageNameList"
        },
        "showWorkContactsInPersonalProfile": {
          "type": "string",
          "enum": [
            "SHOW_WORK_CONTACTS_IN_PERSONAL_PROFILE_UNSPECIFIED",
            "SHOW_WORK_CONTACTS_IN_PERSONAL_PROFILE_DISALLOWED",
            "SHOW_WORK_CONTACTS_IN_PERSONAL_PROFILE_ALLOWED",
            "SHOW_WORK_CONTACTS_IN_PERSONAL_PROFILE_DISALLOWED_EXCEPT_SYSTEM"
          ]
        },
        "workProfileWidgetsDefault": {
          "type": "string",
          "enum": [
            "WORK_PROFILE_WIDGETS_DEFAULT_UNSPECIFIED",
            "WORK_PROFILE_WIDGETS_DEFAULT_ALLOWED",
            "WORK_PROFILE_WIDGETS_DEFAULT_DISALLOWED"
          ]
        }
      }
    },
    "CustomAppConfig": {
      "type": "object",
      "properties": {
        "userUninstallSettings": {
          "type": "string",
          "enum": [
            "USER_UNINSTALL_SETTINGS_UNSPECIFIED",
            "DISALLOW_UNINSTALL_BY_USER",
            "ALLOW_UNINSTALL_BY_USER"
          ]
        }
      }
    },
    "Date": {
      "type": "object",
      "properties": {
        "day": {
          "type": "integer",
          "format": "int32"
        },
        "month": {
          "type": "integer",
          "format": "int32"
        },
        "year": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "DefaultApplication": {
      "type": "object",
      "properties": {
        "packageName": {
          "type": "string"
        }
      }
    },
    "DefaultApplicationSetting": {
      "type": "object",
      "properties": {
        "defaultApplications": {
          "type": "array",
          "items": {
            "$ref": "DefaultApplication"
          }
        },
        "defaultApplicationScopes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "DEFAULT_APPLICATION_SCOPE_UNSPECIFIED",
              "SCOPE_FULLY_MANAGED",
              "SCOPE_WORK_PROFILE",
              "SCOPE_PERSONAL_PROFILE"
            ]
          }
        },
        "defaultApplicationType": {
          "type": "string",
          "enum": [
            "DEFAULT_APPLICATION_TYPE_UNSPECIFIED",
            "DEFAULT_ASSISTANT",
            "DEFAULT_BROWSER",
            "DEFAULT_CALL_REDIRECTION",
            "DEFAULT_CALL_SCREENING",
            "DEFAULT_DIALER",
            "DEFAULT_HOME",
            "DEFAULT_SMS",
            "DEFAULT_WALLET"
          ]
        }
      }
    },
    "DeviceConnectivityManagement": {
      "type": "object",
      "properties": {
        "apnPolicy": {
          "$ref": "ApnPolicy"
        },
        "bluetoothSharing": {
          "type": "string",
          "enum": [
            "BLUETOOTH_SHARING_UNSPECIFIED",
            "BLUETOOTH_SHARING_ALLOWED",
            "BLUETOOTH_SHARING_DISALLOWED"
          ]
        },
        "configureWifi": {
          "type": "string",
          "enum": [
            "CONFIGURE_WIFI_UNSPECIFIED",
            "ALLOW_CONFIGURING_WIFI",
            "DISALLOW_ADD_WIFI_CONFIG",
            "DISALLOW_CONFIGURING_WIFI"
          ]
        },
        "preferentialNetworkServiceSettings": {
          "$ref": "PreferentialNetworkServiceSettings"
        },
        "privateDnsSettings": {
          "$ref": "PrivateDnsSettings"
        },
        "tetheringSettings": {
          "type": "string",
          "enum": [
            "TETHERING_SETTINGS_UNSPECIFIED",
            "ALLOW_ALL_TETHERING",
            "DISALLOW_WIFI_TETHERING",
            "DISALLOW_ALL_TETHERING"
          ]
        },
        "usbDataAccess": {
          "type": "string",
          "enum": [
            "USB_DATA_ACCESS_UNSPECIFIED",
            "ALLOW_USB_DATA_TRANSFER",
            "DISALLOW_USB_FILE_TRANSFER",
            "DISALLOW_USB_DATA_TRANSFER"
          ]
        },
        "wifiDirectSettings": {
          "type": "string",
          "enum": [
            "WIFI_DIRECT_SETTINGS_UNSPECIFIED",
            "ALLOW_WIFI_DIRECT",
            "DISALLOW_WIFI_DIRECT"
          ]
        },
        "wifiRoamingPolicy": {
          "$ref": "WifiRoamingPolicy"
        },
        "wifiSsidPolicy": {
          "$ref": "WifiSsidPolicy"
        }
      }
    },
    "DeviceRadioState": {
      "type": "object",
      "properties": {
        "airplaneModeState": {
          "type": "string",
          "enum": [
            "AIRPLANE_MODE_STATE_UNSPECIFIED",
            "AIRPLANE_MODE_USER_CHOICE",
            "AIRPLANE_MODE_DISABLED"
          ]
        },
        "cellularTwoGState": {
          "type": "string",
          "enum": [
            "CELLULAR_TWO_G_STATE_UNSPECIFIED",
            "CELLULAR_TWO_G_USER_CHOICE",
            "CELLULAR_TWO_G_DISABLED"
          ]
        },
        "minimumWifiSecurityLevel": {
          "type": "string",
          "enum": [
            "MINIMUM_WIFI_SECURITY_LEVEL_UNSPECIFIED",
            "OPEN_NETWORK_SECURITY",
            "PERSONAL_NETWORK_SECURITY",
            "ENTERPRISE_NETWORK_SECURITY",
            "ENTERPRISE_BIT192_NETWORK_SECURITY"
          ]
        },
        "ultraWidebandState": {
          "type": "string",
          "enum": [
            "ULTRA_WIDEBAND_STATE_UNSPECIFIED",
            "ULTRA_WIDEBAND_USER_CHOICE",
            "ULTRA_WIDEBAND_DISABLED"
          ]
        },
        "userInitiatedAddEsimSettings": {
          "type": "string",
          "enum": [
            "USER_INITIATED_ADD_ESIM_SETTINGS_UNSPECIFIED",
            "USER_INITIATED_ADD_ESIM_ALLOWED",
            "USER_INITIATED_ADD_ESIM_DISALLOWED"
          ]
        },
        "wifiState": {
          "type": "string",
          "enum": [
            "WIFI_STATE_UNSPECIFIED",
            "WIFI_STATE_USER_CHOICE",
            "WIFI_ENABLED",
            "WIFI_DISABLED"
          ]
        }
      }
    },
    "DisplaySettings": {
      "type": "object",
      "properties": {
        "screenBrightnessSettings": {
          "$ref": "ScreenBrightnessSettings"
        },
        "screenTimeoutSettings": {
          "$ref": "ScreenTimeoutSettings"
        }
      }
    },
    "ExtensionConfig": {
      "type": "object",
      "properties": {
        "notificationReceiver": {
          "type": "string"
        },
        "signingKeyFingerprintsSha256": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "FreezePeriod": {
      "type": "object",
      "properties": {
        "endDate": {
          "$ref": "Date"
        },
        "startDate": {
          "$ref": "Date"
        }
      }
    },
    "InstallConstraint": {
      "type": "object",
      "properties": {
        "chargingConstraint": {
          "type": "string",
          "enum": [
            "CHARGING_CONSTRAINT_UNSPECIFIED",
            "CHARGING_NOT_REQUIRED",
            "INSTALL_ONLY_WHEN_CHARGING"
          ]
        },
        "deviceIdleConstraint": {
          "type": "string",
          "enum": [
            "DEVICE_IDLE_CONSTRAINT_UNSPECIFIED",
            "DEVICE_IDLE_NOT_REQUIRED",
            "INSTALL_ONLY_WHEN_DEVICE_IDLE"
          ]
        },
        "networkTypeConstraint": {
          "type": "string",
          "enum": [
            "NETWORK_TYPE_CONSTRAINT_UNSPECIFIED",
            "INSTALL_ON_ANY_NETWORK",
            "INSTALL_ONLY_ON_UNMETERED_NETWORK"
          ]
        }
      }
    },
    "KioskCustomization": {
      "type": "object",
      "properties": {
        "deviceSettings": {
          "type": "string",
          "enum": [
            "DEVICE_SETTINGS_UNSPECIFIED",
            "SETTINGS_ACCESS_ALLOWED",
            "SETTINGS_ACCESS_BLOCKED"
          ]
        },
        "powerButtonActions": {
          "type": "string",
          "enum": [
            "POWER_BUTTON_ACTIONS_UNSPECIFIED",
            "POWER_BUTTON_AVAILABLE",
            "POWER_BUTTON_BLOCKED"
          ]
        },
        "statusBar": {
          "type": "string",
          "enum": [
            "STATUS_BAR_UNSPECIFIED",
            "NOTIFICATIONS_AND_SYSTEM_INFO_ENABLED",
            "NOTIFICATIONS_AND_SYSTEM_INFO_DISABLED",
            "SYSTEM_INFO_ONLY"
          ]
        },
        "systemErrorWarnings": {
          "type": "string",
          "enum": [
            "SYSTEM_ERROR_WARNINGS_UNSPECIFIED",
            "ERROR_AND_WARNINGS_ENABLED",
            "ERROR_AND_WARNINGS_MUTED"
          ]
        },
        "systemNavigation": {
          "type": "string",
          "enum": [
            "SYSTEM_NAVIGATION_UNSPECIFIED",
            "NAVIGATION_ENABLED",
            "NAVIGATION_DISABLED",
            "HOME_BUTTON_ONLY"
          ]
        }
      }
    },
    "LaunchAppAction": {
      "type": "object",
      "properties": {
        "packageName": {
          "type": "string"
        }
      }
    },
    "ManagedConfigurationTemplate": {
      "type": "object",
      "properties": {
        "configurationVariables": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "templateId": {
          "type": "string"
        }
      }
    },
    "NonComplianceDetailCondition": {
      "type": "object",
      "properties": {
        "nonComplianceReason": {
          "type": "string",
          "enum": [
            "NON_COMPLIANCE_REASON_UNSPECIFIED",
            "API_LEVEL",
            "MANAGEMENT_MODE",
            "USER_ACTION",
            "INVALID_VALUE",
            "APP_NOT_INSTALLED",
            "UNSUPPORTED",
            "APP_INSTALLED",
            "PENDING",
            "APP_INCOMPATIBLE",
            "APP_NOT_UPDATED",
            "DEVICE_INCOMPATIBLE",
            "APP_SIGNING_CERT_MISMATCH",
            "PROJECT_NOT_PERMITTED"
          ]
        },
        "packageName": {
          "type": "string"
        },
        "settingName": {
          "type": "string"
        }
      }
    },
    "OncCertificateProvider": {
      "type": "object",
      "properties": {
        "certificateReferences": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contentProviderEndpoint": {
          "$ref": "ContentProviderEndpoint"
        }
      }
    },
    "PackageNameList": {
      "type": "object",
      "properties": {
        "packageNames": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "PasswordRequirements": {
      "type": "object",
      "properties": {
        "maximumFailedPasswordsForWipe": {
          "type": "integer",
          "format": "int32"
        },
        "passwordExpirationTimeout": {
          "type": "string",
          "format": "google-duration"
        },
        "passwordHistoryLength": {
          "type": "integer",
          "format": "int32"
        },
        "passwordMinimumLength": {
          "type": "integer",
          "format": "int32"
        },
        "passwordMinimumLetters": {
          "type": "integer",
          "format": "int32"
        },
        "passwordMinimumLowerCase": {
          "type": "integer",
          "format": "int32"
        },
        "passwordMinimumNonLetter": {
          "type": "integer",
          "format": "int32"
        },
        "passwordMinimumNumeric": {
          "type": "integer",
          "format": "int32"
        },
        "passwordMinimumSymbols": {
          "type": "integer",
          "format": "int32"
        },
        "passwordMinimumUpperCase": {
          "type": "integer",
          "format": "int32"
        },
        "passwordQuality": {
          "type": "string",
          "enum": [
            "PASSWORD_QUALITY_UNSPECIFIED",
            "BIOMETRIC_WEAK",
            "SOMETHING",
            "NUMERIC",
            "NUMERIC_COMPLEX",
            "ALPHABETIC",
            "ALPHANUMERIC",
            "COMPLEX",
            "COMPLEXITY_LOW",
            "COMPLEXITY_MEDIUM",
            "COMPLEXITY_HIGH"
          ]
        },
        "passwordScope": {
          "type": "string",
          "enum": [
            "SCOPE_UNSPECIFIED",
            "SCOPE_DEVICE",
            "SCOPE_PROFILE"
          ]
        },
        "requirePasswordUnlock": {
          "type": "string",
          "enum": [
            "REQUIRE_PASSWORD_UNLOCK_UNSPECIFIED",
            "USE_DEFAULT_DEVICE_TIMEOUT",
            "REQUIRE_EVERY_DAY"
          ]
        },
        "unifiedLockSettings": {
          "type": "string",
          "enum": [
            "UNIFIED_LOCK_SETTINGS_UNSPECIFIED",
            "ALLOW_UNIFIED_WORK_AND_PERSONAL_LOCK",
            "REQUIRE_SEPARATE_WORK_LOCK"
          ]
        }
      }
    },
    "PermissionGrant": {
      "type": "object",
      "properties": {
        "permission": {
          "type": "string"
        },
        "policy": {
          "type": "string",
          "enum": [
            "PERMISSION_POLICY_UNSPECIFIED",
            "PROMPT",
            "GRANT",
            "DENY"
          ]
        }
      }
    },
    "PersistentPreferredActivity": {
      "type": "object",
      "properties": {
        "actions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "receiverActivity": {
          "type": "string"
        }
      }
    },
    "PersonalApplicationPolicy": {
      "type": "object",
      "properties": {
        "installType": {
          "type": "string",
          "enum": [
            "INSTALL_TYPE_UNSPECIFIED",
            "BLOCKED",
            "AVAILABLE"
          ]
        },
        "packageName": {
          "type": "string"
        }
      }
    },
    "PersonalUsagePolicies": {
      "type": "object",
      "properties": {
        "accountTypesWithManagementDisabled": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "bluetoothSharing": {
          "type": "string",
          "enum": [
            "BLUETOOTH_SHARING_UNSPECIFIED",
            "BLUETOOTH_SHARING_ALLOWED",
            "BLUETOOTH_SHARING_DISALLOWED"
          ]
        },
        "cameraDisabled": {
          "type": "boolean"
        },
        "maxDaysWithWorkOff": {
          "type": "integer",
          "format": "int32"
        },
        "personalApplications": {
          "type": "array",
          "items": {
            "$ref": "PersonalApplicationPolicy"
          }
        },
        "personalPlayStoreMode": {
          "type": "string",
          "enum": [
            "PLAY_STORE_MODE_UNSPECIFIED",
            "BLACKLIST",
            "BLOCKLIST",
            "ALLOWLIST"
          ]
        },
        "privateSpacePolicy": {
          "type": "string",
          "enum": [
            "PRIVATE_SPACE_POLICY_UNSPECIFIED",
            "PRIVATE_SPACE_ALLOWED",
            "PRIVATE_SPACE_DISALLOWED"
          ]
        },
        "screenCaptureDisabled": {
          "type": "boolean"
        }
      }
    },
    "Policy": {
      "type": "object",
      "properties": {
        "accountTypesWithManagementDisabled": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "addUserDisabled": {
          "type": "boolean"
        },
        "adjustVolumeDisabled": {
          "type": "boolean"
        },
        "advancedSecurityOverrides": {
          "$ref": "AdvancedSecurityOverrides"
        },
        "alwaysOnVpnPackage": {
          "$ref": "AlwaysOnVpnPackage"
        },
        "androidDevicePolicyTracks": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "APP_TRACK_UNSPECIFIED",
              "PRODUCTION",
              "BETA"
            ]
          }
        },
        "appAutoUpdatePolicy": {
          "type": "string",
          "enum": [
            "APP_AUTO_UPDATE_POLICY_UNSPECIFIED",
            "CHOICE_TO_THE_USER",
            "NEVER",
            "WIFI_ONLY",
            "ALWAYS"
          ]
        },
        "appFunctions": {
          "type": "string",
          "enum": [
            "APP_FUNCTIONS_UNSPECIFIED",
            "APP_FUNCTIONS_DISALLOWED",
            "APP_FUNCTIONS_ALLOWED"
          ]
        },
        "applications": {
          "type": "array",
          "items": {
            "$ref": "ApplicationPolicy"
          }
        },
        "assistContentPolicy": {
          "type": "string",
          "enum": [
            "ASSIST_CONTENT_POLICY_UNSPECIFIED",
            "ASSIST_CONTENT_DISALLOWED",
            "ASSIST_CONTENT_ALLOWED"
          ]
        },
        "autoDateAndTimeZone": {
          "type": "string",
          "enum": [
            "AUTO_DATE_AND_TIME_ZONE_UNSPECIFIED",
            "AUTO_DATE_AND_TIME_ZONE_USER_CHOICE",
            "AUTO_DATE_AND_TIME_ZONE_ENFORCED"
          ]
        },
        "autofillPolicy": {
          "type": "string",
          "enum": [
            "AUTOFILL_POLICY_UNSPECIFIED",
            "AUTOFILL_USER_CHOICE",
            "AUTOFILL_DISABLED"
          ]
        },
        "autoTimeRequired": {
          "type": "boolean"
        },
        "blockApplicationsEnabled": {
          "type": "boolean"
        },
        "bluetoothConfigDisabled": {
          "type": "boolean"
        },
        "bluetoothContactSharingDisabled": {
          "type": "boolean"
        },
        "bluetoothDisabled": {
          "type": "boolean"
        },
        "cameraAccess": {
          "type": "string",
          "enum": [
            "CAMERA_ACCESS_UNSPECIFIED",
            "CAMERA_ACCESS_USER_CHOICE",
            "CAMERA_ACCESS_DISABLED",
            "CAMERA_ACCESS_ENFORCED"
          ]
        },
        "cameraDisabled": {
          "type": "boolean"
        },
        "cellBroadcastsConfigDisabled": {
          "type": "boolean"
        },
        "choosePrivateKeyRules": {
          "type": "array",
          "items": {
            "$ref": "ChoosePrivateKeyRule"
          }
        },
        "complianceRules": {
          "type": "array",
          "items": {
            "$ref": "ComplianceRule"
          }
        },
        "createWindowsDisabled": {
          "type": "boolean"
        },
        "credentialProviderPolicyDefault": {
          "type": "string",
          "enum": [
            "CREDENTIAL_PROVIDER_POLICY_DEFAULT_UNSPECIFIED",
            "CREDENTIAL_PROVIDER_DEFAULT_DISALLOWED",
            "CREDENTIAL_PROVIDER_DEFAULT_DISALLOWED_EXCEPT_SYSTEM",
            "CREDENTIAL_PROVIDER_DEFAULT_ALLOWED"
          ]
        },
        "credentialsConfigDisabled": {
          "type": "boolean"
        },
        "crossDevicePolicies": {
          "$ref": "CrossDevicePolicies"
        },
        "crossProfilePolicies": {
          "$ref": "CrossProfilePolicies"
        },
        "dataRoamingDisabled": {
          "type": "boolean"
        },
        "debuggingFeaturesAllowed": {
          "type": "boolean"
        },
        "defaultApplicationSettings": {
          "type": "array",
          "items": {
            "$ref": "DefaultApplicationSetting"
          }
        },
        "defaultPermissionPolicy": {
          "type": "string",
          "enum": [
            "PERMISSION_POLICY_UNSPECIFIED",
            "PROMPT",
            "GRANT",
            "DENY"
          ]
        },
        "deviceConnectivityManagement": {
          "$ref": "DeviceConnectivityManagement"
        },
        "deviceOwnerLockScreenInfo": {
          "$ref": "UserFacingMessage"
        },
        "deviceRadioState": {
          "$ref": "DeviceRadioState"
        },
        "displaySettings": {
          "$ref": "DisplaySettings"
        },
        "encryptionPolicy": {
          "type": "string",
          "enum": [
            "ENCRYPTION_POLICY_UNSPECIFIED",
            "ENABLED_WITHOUT_PASSWORD",
            "ENABLED_WITH_PASSWORD"
          ]
        },
        "ensureVerifyAppsEnabled": {
          "type": "boolean"
        },
        "enterpriseDisplayNameVisibility": {
          "type": "string",
          "enum": [
            "ENTERPRISE_DISPLAY_NAME_VISIBILITY_UNSPECIFIED",
            "ENTERPRISE_DISPLAY_NAME_VISIBLE",
            "ENTERPRISE_DISPLAY_NAME_HIDDEN"
          ]
        },
        "factoryResetDisabled": {
          "type": "boolean"
        },
        "frpAdminEmails": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "funDisabled": {
          "type": "boolean"
        },
        "installAppsDisabled": {
          "type": "boolean"
        },
        "installUnknownSourcesAllowed": {
          "type": "boolean"
        },
        "keyguardDisabled": {
          "type": "boolean"
        },
        "keyguardDisabledFeatures": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "KEYGUARD_DISABLED_FEATURE_UNSPECIFIED",
              "CAMERA",
              "NOTIFICATIONS",
              "UNREDACTED_NOTIFICATIONS",
              "TRUST_AGENTS",
              "DISABLE_FINGERPRINT",
              "DISABLE_REMOTE_INPUT",
              "FACE",
              "IRIS",
              "BIOMETRICS",
              "SHORTCUTS",
              "ALL_FEATURES"
            ]
          }
        },
        "kioskCustomization": {
          "$ref": "KioskCustomization"
        },
        "kioskCustomLauncherEnabled": {
          "type": "boolean"
        },
        "locationMode": {
          "type": "string",
          "enum": [
            "LOCATION_MODE_UNSPECIFIED",
            "HIGH_ACCURACY",
            "SENSORS_ONLY",
            "BATTERY_SAVING",
            "OFF",
            "LOCATION_USER_CHOICE",
            "LOCATION_ENFORCED",
            "LOCATION_DISABLED"
          ]
        },
        "longSupportMessage": {
          "$ref": "UserFacingMessage"
        },
        "maximumTimeToLock": {
          "type": "string",
          "format": "int64"
        },
        "microphoneAccess": {
          "type": "string",
          "enum": [
            "MICROPHONE_ACCESS_UNSPECIFIED",
            "MICROPHONE_ACCESS_USER_CHOICE",
            "MICROPHONE_ACCESS_DISABLED",
            "MICROPHONE_ACCESS_ENFORCED"
          ]
        },
        "minimumApiLevel": {
          "type": "integer",
          "format": "int32"
        },
        "mobileNetworksConfigDisabled": {
          "type": "boolean"
        },
        "modifyAccountsDisabled": {
          "type": "boolean"
        },
        "mountPhysicalMediaDisabled": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "networkEscapeHatchEnabled": {
          "type": "boolean"
        },
        "networkResetDisabled": {
          "type": "boolean"
        },
        "oncCertificateProviders": {
          "type": "array",
          "items": {
            "$ref": "OncCertificateProvider"
          }
        },
        "openNetworkConfiguration": {
          "type": "object",
          "additionalProperties": {
            "type": "any"
          }
        },
        "outgoingBeamDisabled": {
          "type": "boolean"
        },
        "outgoingCallsDisabled": {
          "type": "boolean"
        },
        "passwordPolicies": {
          "type": "array",
          "items": {
            "$ref": "PasswordRequirements"
          }
        },
        "passwordRequirements": {
          "$ref": "PasswordRequirements"
        },
        "permissionGrants": {
          "type": "array",
          "items": {
            "$ref": "PermissionGrant"
          }
        },
        "permittedAccessibilityServices": {
          "$ref": "PackageNameList"
        },
        "permittedInputMethods": {
          "$ref": "PackageNameList"
        },
        "persistentPreferredActivities": {
          "type": "array",
          "items": {
            "$ref": "PersistentPreferredActivity"
          }
        },
        "personalUsagePolicies": {
          "$ref": "PersonalUsagePolicies"
        },
        "playStoreMode": {
          "type": "string",
          "enum": [
            "PLAY_STORE_MODE_UNSPECIFIED",
            "WHITELIST",
            "BLACKLIST"
          ]
        },
        "policyEnforcementRules": {
          "type": "array",
          "items": {
            "$ref": "PolicyEnforcementRule"
          }
        },
        "preferentialNetworkService": {
          "type": "string",
          "enum": [
            "PREFERENTIAL_NETWORK_SERVICE_UNSPECIFIED",
            "PREFERENTIAL_NETWORK_SERVICE_DISABLED",
            "PREFERENTIAL_NETWORK_SERVICE_ENABLED"
          ]
        },
        "printingPolicy": {
          "type": "string",
          "enum": [
            "PRINTING_POLICY_UNSPECIFIED",
            "PRINTING_DISALLOWED",
            "PRINTING_ALLOWED"
          ]
        },
        "privateKeySelectionEnabled": {
          "type": "boolean"
        },
        "recommendedGlobalProxy": {
          "$ref": "ProxyInfo"
        },
        "removeUserDisabled": {
          "type": "boolean"
        },
        "safeBootDisabled": {
          "type": "boolean"
        },
        "screenCaptureDisabled": {
          "type": "boolean"
        },
        "setupActions": {
          "type": "array",
          "items": {
            "$ref": "SetupAction"
          }
        },
        "setUserIconDisabled": {
          "type": "boolean"
        },
        "setWallpaperDisabled": {
          "type": "boolean"
        },
        "shareLocationDisabled": {
          "type": "boolean"
        },
        "shortSupportMessage": {
          "$ref": "UserFacingMessage"
        },
        "skipFirstUseHintsEnabled": {
          "type": "boolean"
        },
        "smsDisabled": {
          "type": "boolean"
        },
        "statusBarDisabled": {
          "type": "boolean"
        },
        "statusReportingSettings": {
          "$ref": "StatusReportingSettings"
        },
        "stayOnPluggedModes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "BATTERY_PLUGGED_MODE_UNSPECIFIED",
              "AC",
              "USB",
              "WIRELESS"
            ]
          }
        },
        "systemUpdate": {
          "$ref": "SystemUpdate"
        },
        "tetheringConfigDisabled": {
          "type": "boolean"
        },
        "uninstallAppsDisabled": {
          "type": "boolean"
        },
        "unmuteMicrophoneDisabled": {
          "type": "boolean"
        },
        "usageLog": {
          "$ref": "UsageLog"
        },
        "usbFileTransferDisabled": {
          "type": "boolean"
        },
        "usbMassStorageEnabled": {
          "type": "boolean"
        },
        "version": {
          "type": "string",
          "format": "int64"
        },
        "vpnConfigDisabled": {
          "type": "boolean"
        },
        "wifiConfigDisabled": {
          "type": "boolean"
        },
        "wifiConfigsLockdownEnabled": {
          "type": "boolean"
        },
        "wipeDataFlags": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "WIPE_DATA_FLAG_UNSPECIFIED",
              "WIPE_ESIMS"
            ]
          }
        },
        "workAccountSetupConfig": {
          "$ref": "WorkAccountSetupConfig"
        }
      }
    },
    "PolicyEnforcementRule": {
      "type": "object",
      "properties": {
        "blockAction": {
          "$ref": "BlockAction"
        },
        "settingName": {
          "type": "string"
        },
        "wipeAction": {
          "$ref": "WipeAction"
        }
      }
    },
    "PreferentialNetworkServiceConfig": {
      "type": "object",
      "properties": {
        "fallbackToDefaultConnection": {
          "type": "string",
          "enum": [
            "FALLBACK_TO_DEFAULT_CONNECTION_UNSPECIFIED",
            "FALLBACK_TO_DEFAULT_CONNECTION_ALLOWED",
            "FALLBACK_TO_DEFAULT_CONNECTION_DISALLOWED"
          ]
        },
        "nonMatchingNetworks": {
          "type": "string",
          "enum": [
            "NON_MATCHING_NETWORKS_UNSPECIFIED",
            "NON_MATCHING_NETWORKS_ALLOWED",
            "NON_MATCHING_NETWORKS_DISALLOWED"
          ]
        },
        "preferentialNetworkId": {
          "type": "string",
          "enum": [
            "PREFERENTIAL_NETWORK_ID_UNSPECIFIED",
            "NO_PREFERENTIAL_NETWORK",
            "PREFERENTIAL_NETWORK_ID_ONE",
            "PREFERENTIAL_NETWORK_ID_TWO",
            "PREFERENTIAL_NETWORK_ID_THREE",
            "PREFERENTIAL_NETWORK_ID_FOUR",
            "PREFERENTIAL_NETWORK_ID_FIVE"
          ]
        }
      }
    },
    "PreferentialNetworkServiceSettings": {
      "type": "object",
      "properties": {
        "defaultPreferentialNetworkId": {
          "type": "string",
          "enum": [
            "PREFERENTIAL_NETWORK_ID_UNSPECIFIED",
            "NO_PREFERENTIAL_NETWORK",
            "PREFERENTIAL_NETWORK_ID_ONE",
            "PREFERENTIAL_NETWORK_ID_TWO",
            "PREFERENTIAL_NETWORK_ID_THREE",
            "PREFERENTIAL_NETWORK_ID_FOUR",
            "PREFERENTIAL_NETWORK_ID_FIVE"
          ]
        },
        "preferentialNetworkServiceConfigs": {
          "type": "array",
          "items": {
            "$ref": "PreferentialNetworkServiceConfig"
          }
        }
      }
    },
    "PrivateDnsSettings": {
      "type": "object",
      "properties": {
        "privateDnsHost": {
          "type": "string"
        },
        "privateDnsMode": {
          "type": "string",
          "enum": [
            "PRIVATE_DNS_MODE_UNSPECIFIED",
            "PRIVATE_DNS_USER_CHOICE",
            "PRIVATE_DNS_AUTOMATIC",
            "PRIVATE_DNS_SPECIFIED_HOST"
          ]
        }
      }
    },
    "ProxyInfo": {
      "type": "object",
      "properties": {
        "excludedHosts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "host": {
          "type": "string"
        },
        "pacUri": {
          "type": "string"
        },
        "port": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "Role": {
      "type": "object",
      "properties": {
        "roleType": {
          "type": "string",
          "enum": [
            "ROLE_TYPE_UNSPECIFIED",
            "COMPANION_APP",
            "KIOSK",
            "MOBILE_THREAT_DEFENSE_ENDPOINT_DETECTION_RESPONSE",
            "SYSTEM_HEALTH_MONITORING"
          ]
        }
      }
    },
    "ScreenBrightnessSettings": {
      "type": "object",
      "properties": {
        "screenBrightness": {
          "type": "integer",
          "format": "int32"
        },
        "screenBrightnessMode": {
          "type": "string",
          "enum": [
            "SCREEN_BRIGHTNESS_MODE_UNSPECIFIED",
            "BRIGHTNESS_USER_CHOICE",
            "BRIGHTNESS_AUTOMATIC",
            "BRIGHTNESS_FIXED"
          ]
        }
      }
    },
    "ScreenTimeoutSettings": {
      "type": "object",
      "properties": {
        "screenTimeout": {
          "type": "string",
          "format": "google-duration"
        },
        "screenTimeoutMode": {
          "type": "string",
          "enum": [
            "SCREEN_TIMEOUT_MODE_UNSPECIFIED",
            "SCREEN_TIMEOUT_USER_CHOICE",
            "SCREEN_TIMEOUT_ENFORCED"
          ]
        }
      }
    },
    "SetupAction": {
      "type": "object",
      "properties": {
        "description": {
          "$ref": "UserFacingMessage"
        },
        "launchApp": {
          "$ref": "LaunchAppAction"
        },
        "title": {
          "$ref": "UserFacingMessage"
        }
      }
    },
    "StatusReportingSettings": {
      "type": "object",
      "properties": {
        "applicationReportingSettings": {
          "$ref": "ApplicationReportingSettings"
        },
        "applicationReportsEnabled": {
          "type": "boolean"
        },
        "commonCriteriaModeEnabled": {
          "type": "boolean"
        },
        "defaultApplicationInfoReportingEnabled": {
          "type": "boolean"
        },
        "deviceSettingsEnabled": {
          "type": "boolean"
        },
        "displayInfoEnabled": {
          "type": "boolean"
        },
        "hardwareStatusEnabled": {
          "type": "boolean"
        },
        "memoryInfoEnabled": {
          "type": "boolean"
        },
        "networkInfoEnabled": {
          "type": "boolean"
        },
        "powerManagementEventsEnabled": {
          "type": "boolean"
        },
        "softwareInfoEnabled": {
          "type": "boolean"
        },
        "systemPropertiesEnabled": {
          "type": "boolean"
        }
      }
    },
    "SystemUpdate": {
      "type": "object",
      "properties": {
        "endMinutes": {
          "type": "integer",
          "format": "int32"
        },
        "freezePeriods": {
          "type": "array",
          "items": {
            "$ref": "FreezePeriod"
          }
        },
        "startMinutes": {
          "type": "integer",
          "format": "int32"
        },
        "type": {
          "type": "string",
          "enum": [
            "SYSTEM_UPDATE_TYPE_UNSPECIFIED",
            "AUTOMATIC",
            "WINDOWED",
            "POSTPONE"
          ]
        }
      }
    },
    "UsageLog": {
      "type": "object",
      "properties": {
        "enabledLogTypes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "LOG_TYPE_UNSPECIFIED",
              "SECURITY_LOGS",
              "NETWORK_ACTIVITY_LOGS"
            ]
          }
        },
        "uploadOnCellularAllowed": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "LOG_TYPE_UNSPECIFIED",
              "SECURITY_LOGS",
              "NETWORK_ACTIVITY_LOGS"
            ]
          }
        }
      }
    },
    "UserFacingMessage": {
      "type": "object",
      "properties": {
        "defaultMessage": {
          "type": "string"
        },
        "localizedMessages": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "WifiRoamingPolicy": {
      "type": "object",
      "properties": {
        "wifiRoamingSettings": {
          "type": "array",
          "items": {
            "$ref": "WifiRoamingSetting"
          }
        }
      }
    },
    "WifiRoamingSetting": {
      "type": "object",
      "properties": {
        "wifiRoamingMode": {
          "type": "string",
          "enum": [
            "WIFI_ROAMING_MODE_UNSPECIFIED",
            "WIFI_ROAMING_DISABLED",
            "WIFI_ROAMING_DEFAULT",
            "WIFI_ROAMING_AGGRESSIVE"
          ]
        },
        "wifiSsid": {
          "type": "string"
        }
      }
    },
    "WifiSsid": {
      "type": "object",
      "properties": {
        "wifiSsid": {
          "type": "string"
        }
      }
    },
    "WifiSsidPolicy": {
      "type": "object",
      "properties": {
        "wifiSsidPolicyType": {
          "type": "string",
          "enum": [
            "WIFI_SSID_POLICY_TYPE_UNSPECIFIED",
            "WIFI_SSID_DENYLIST",
            "WIFI_SSID_ALLOWLIST"
          ]
        },
        "wifiSsids": {
          "type": "array",
          "items": {
            "$ref": "WifiSsid"
          }
        }
      }
    },
    "WipeAction": {
      "type": "object",
      "properties": {
        "preserveFrp": {
          "type": "boolean"
        },
        "wipeAfterDays": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "WorkAccountSetupConfig": {
      "type": "object",
      "properties": {
        "authenticationType": {
          "type": "string",
          "enum": [
            "AUTHENTICATION_TYPE_UNSPECIFIED",
            "AUTHENTICATION_TYPE_NOT_ENFORCED",
            "GOOGLE_AUTHENTICATED"
          ]
        },
        "requiredAccountEmail": {
          "type": "string"
        }
      }
    }
  }
} as const;
